default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: laraveljj
  password: P0werS1p**@eu!
  host: 169.57.252.205

development:
  <<: *default
  database: junto

test:
  <<: *default
  database: junto